---
- name: Create User Account
  hosts: your_target_machine
  become: yes # Run tasks with sudo (root) privileges

  vars:
    username: newuser
    password: "{{ 'your_password' }}" 

  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        state: present
        groups: wheel #  can customize additional groups as per requirement
        shell: /bin/bash #  can change the shell if needed

    - name: Add SSH key to authorized_keys
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" # Need to use this path to for my SSH public key file

    - name: Set up sudo privileges
      lineinfile:
        dest: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s" 


    
